backend:
  name: git-gateway
  branch: main
  repo: GoWeb-Internship/e-volunteer
media_folder: 'static/img'
public_folder: '/img'
collections:
  # Cards
  - label: 'Cards_RU'
    name: 'cards_ru'
    folder: 'content/cards'
    label_singular: 'Cards_RU'
    slug: '{{fields.slug}}'
    create: true
    path: '{{folder}}/{{language}}'
    filter: { field: 'language', value: 'ru' }
    fields:
      - { label: 'Folder', name: 'folder', widget: 'string' }

      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['ru'],
          default: 'ru',
        }
      - label: 'Links'
        name: 'links'
        widget: list
        fields:
          - { label: 'Href', name: 'href', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Cards_UA'
    name: 'cards_ua'
    folder: 'content/cards'
    label_singular: 'Cards_UA'
    slug: '{{fields.slug}}'
    create: true
    path: '{{folder}}/{{language}}'
    filter: { field: 'language', value: 'uk' }
    fields:
      - { label: 'Folder', name: 'folder', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['uk'],
          default: 'uk',
        }
