backend:
  name: git-gateway
  branch: main
  repo: GoWeb-Internship/e-volunteer
media_folder: 'public/static/img'
public_folder: '/img'
collections:
  # Categories
  - label: 'Categories_RU'
    name: 'categories_ru'
    folder: 'content/categories'
    label_singular: 'Categories_RU'
    slug: '{{fields.slug}}'
    create: true
    delete: false
    path: '{{category}}/{{language}}'
    filter: { field: 'language', value: 'ru' }
    fields:
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options:
            [
              { label: 'Первые шаги', value: 'registration' },
              { label: 'Жильё', value: 'housing' },
              { label: 'Работа', value: 'work' },
              { label: 'Медицинская помощь', value: 'medicine' },
              { label: 'Психологическая помощь', value: 'counselling' },
              { label: 'Дети', value: 'kids' },
              { label: 'Выплаты', value: 'payments' },
              { label: 'Инфо телефоны', value: 'info' },
              { label: 'Полезные ссылки', value: 'references' },
            ],
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Poster', name: 'poster', widget: 'image', choose_url: true }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['ru'],
          default: 'ru',
        }
      - { label: 'Date', name: 'date', widget: 'date', format: 'MMM Do YY' }
      # - label: 'Links'
      #   name: 'links'
      #   widget: list
      #   fields:
      #     - { label: 'Href', name: 'href', widget: 'string' }
      #     - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Categories_UA'
    name: 'categories_ua'
    folder: 'content/categories'
    label_singular: 'categories_UA'
    slug: '{{fields.slug}}'
    create: true
    delete: false
    path: '{{category}}/{{language}}'
    filter: { field: 'language', value: 'uk' }
    fields:
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options:
            [
              { label: 'Перші кроки', value: 'registration' },
              { label: 'Житло', value: 'housing' },
              { label: 'Робота', value: 'work' },
              { label: 'Медична допомога', value: 'medicine' },
              { label: 'Психологічна допомога', value: 'counselling' },
              { label: 'Діти', value: 'kids' },
              { label: 'Виплати', value: 'payments' },
              { label: 'Інфо телефони', value: 'info' },
              { label: 'Корисні посилання', value: 'references' },
            ],
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Poster', name: 'poster', widget: 'image', choose_url: true }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['uk'],
          default: 'uk',
        }
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
