backend:
  name: git-gateway
  branch: main
  repo: GoWeb-Internship/e-volunteer
media_folder: 'public/static/img'
public_folder: '/img'
collections:
  # Categories
  - label: 'Categories_RU'
    name: 'categories_ru'
    folder: 'content/categories'
    label_singular: 'Categories_RU'
    slug: '{{fields.slug}}'
    create: true
    delete: true
    path: '{{category}}/{{language}}'
    filter: { field: 'language', value: 'ru' }
    fields:
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options:
            [
              { label: 'Первые шаги', value: 'registration' },
              { label: 'Жильё', value: 'housing' },
              { label: 'Работа', value: 'work' },
              { label: 'Медицинская помощь', value: 'medicine' },
              { label: 'Психологическая помощь', value: 'counselling' },
              { label: 'Дети', value: 'kids' },
              { label: 'Выплаты', value: 'payments' },
              { label: 'Инфо телефоны', value: 'info' },
              { label: 'Полезные ссылки', value: 'references' },
              { label: 'Мастера из Украины', value: 'masters' },
              { label: 'Образование', value: 'education' },
              { label: 'Досуг', value: 'leisure' },
            ],
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Poster', name: 'poster', widget: 'image', choose_url: true }
      - { label: 'Poster Description', name: 'alt', widget: 'string' }
      - { label: 'Preview', name: 'preview', widget: 'string' }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['ru'],
          default: 'ru',
        }
      - { label: 'Range', name: 'range', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Categories_UA'
    name: 'categories_ua'
    folder: 'content/categories'
    label_singular: 'categories_UA'
    slug: '{{fields.slug}}'
    create: true
    delete: true
    path: '{{category}}/{{language}}'
    filter: { field: 'language', value: 'uk' }
    fields:
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options:
            [
              { label: 'Перші кроки', value: 'registration' },
              { label: 'Житло', value: 'housing' },
              { label: 'Робота', value: 'work' },
              { label: 'Медична допомога', value: 'medicine' },
              { label: 'Психологічна допомога', value: 'counselling' },
              { label: 'Діти', value: 'kids' },
              { label: 'Виплати', value: 'payments' },
              { label: 'Інфо телефони', value: 'info' },
              { label: 'Корисні посилання', value: 'references' },
              { label: 'Майстри з України', value: 'masters' },
              { label: 'Освіта', value: 'education' },
              { label: 'Дозвілля', value: 'leisure' },
            ],
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Poster', name: 'poster', widget: 'image', choose_url: true }
      - { label: 'Poster Description', name: 'alt', widget: 'string' }
      - { label: 'Preview', name: 'preview', widget: 'string' }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['uk'],
          default: 'uk',
        }
      - { label: 'Range', name: 'range', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # Help
  - label: 'Help_RU'
    name: 'help_ru'
    folder: 'content/help'
    label_singular: 'Help_RU'
    create: true
    delete: true
    path: '{{language}}'
    filter: { field: 'language', value: 'ru' }
    fields:
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['ru'],
          default: 'ru',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Help_UA'
    name: 'help_ua'
    folder: 'content/help'
    label_singular: 'Help_UA'
    create: true
    delete: true
    path: '{{language}}'
    filter: { field: 'language', value: 'uk' }
    fields:
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['uk'],
          default: 'uk',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # Banner
  - label: 'Banner_RU'
    name: 'banner_ru'
    folder: 'content/banner'
    label_singular: 'Banner_RU'
    create: true
    delete: true
    path: '{{language}}'
    filter: { field: 'language', value: 'ru' }
    fields:
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['ru'],
          default: 'ru',
        }
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          default: Баннер над хедером,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Banner_UA'
    name: 'banner_ua'
    folder: 'content/banner'
    label_singular: 'Banner_UA'
    create: true
    delete: true
    path: '{{language}}'
    filter: { field: 'language', value: 'uk' }
    fields:
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['uk'],
          default: 'uk',
        }
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          default: Банер над хедером,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # Reception Centers
  - label: 'Reception Centers_RU'
    name: 'reception centers_ru'
    folder: 'content/centers'
    label_singular: 'Reception Centers_RU'
    create: true
    delete: true
    path: '{{language}}'
    filter: { field: 'language', value: 'ru' }
    fields:
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['ru'],
          default: 'ru',
        }
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          default: 'Центры приемов беженцев',
        }
      - {
          label: 'List',
          name: 'list',
          widget: 'list',
          fields:
            [
              {
                label: 'Name',
                name: 'name',
                widget: 'string',
                required: false,
              },
              { label: 'City', name: 'city', widget: 'string' },
              { label: 'Address', name: 'address', widget: 'string' },
              { label: 'Tel', name: 'tel', widget: 'string', required: false },
            ],
        }

  - label: 'Reception Centers_UA'
    name: 'reception centers_ua'
    folder: 'content/centers'
    label_singular: 'Reception Centers_UA'
    create: true
    delete: true
    path: '{{language}}'
    filter: { field: 'language', value: 'uk' }
    fields:
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['uk'],
          default: 'uk',
        }
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          default: 'Центри прийомів біженців',
        }
      - {
          label: 'List',
          name: 'list',
          widget: 'list',
          fields:
            [
              {
                label: 'Name',
                name: 'name',
                widget: 'string',
                required: false,
              },
              { label: 'City', name: 'city', widget: 'string' },
              { label: 'Address', name: 'address', widget: 'string' },
              { label: 'Tel', name: 'tel', widget: 'string', required: false },
            ],
        }
  # Footer
  - label: 'Footer_RU'
    name: 'footer_ru'
    folder: 'content/footer'
    label_singular: 'Footer_RU'
    create: true
    delete: true
    path: '{{language}}'
    filter: { field: 'language', value: 'ru' }
    fields:
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['ru'],
          default: 'ru',
        }
      - {
          label: 'Footer',
          name: 'footer',
          widget: 'string',
          default: 'Контакты доп информации',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Footer_UA'
    name: 'footer_ua'
    folder: 'content/footer'
    label_singular: 'Footer_ua'
    create: true
    delete: true
    path: '{{language}}'
    filter: { field: 'language', value: 'uk' }
    fields:
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['uk'],
          default: 'uk',
        }
      - {
          label: 'Footer',
          name: 'footer',
          widget: 'string',
          default: 'Контакти дод інформації',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
