backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'static/img'
public_folder: '/img'

collections:
  - name: 'cards'
    label: 'Cards'
    folder: 'content/cards'
    identifier_field: title
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - {
          label: 'Group identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'index',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['ru', 'uk'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Links'
        name: 'links'
        widget: list
        fields:
          - { label: 'Href', name: 'href', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }

  # - name: 'pages'
  #   label: 'Pages'
  #   files:
  #     - label: 'Home'
  #       name: 'home'
  #       file: 'content/home.md'
  #       slug: '{{test}}'
  #       fields:
  #         - { label: 'Title', name: 'title', widget: 'string' }
  #         - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #         - { label: 'Body', name: 'body', widget: 'markdown' }
  #         - label: 'Cats'
  #           name: 'cats'
  #           widget: list
  #           fields:
  #             - { label: 'Name', name: 'name', widget: 'string' }
  #             - { label: 'Description', name: 'description', widget: 'text' }
